'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def calc_In(x, y):
	return ( 2*x + 3*y )

def calc_In_minus_1(x, y):
	return ( x + 2*y )

def update(x, y):
	return calc_In_minus_1(x, y), calc_In(x, y)

In_minus_1 = 1
In = 2 
Sum = 0
while(True):
	if(In > 4000000):
		break
	Sum += In
	print ( In )
	In_minus_1 ,In = update(In_minus_1, In)	
print (Sum)

a = 1
b = 2
Sum = 0
while(b <= 4000000):
	if ( b % 2 == 0):
		print (b)
		Sum += b
	b = a + b
	a = b - a
print (Sum)
